# === Application Name ===
spring.application.name=youtube-video-summarizer

# === Database Configuration (Local) ===
spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:33464/railway
spring.datasource.username=root
spring.datasource.password=cLkwmqjncDDMuVbhqOQvlWtLKzoFiNoZ

# === JPA & Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# === Server Port ===
server.port=8080

# === HikariCP ===
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
# ==== Email Config ====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sg6640770@gmail.com
spring.mail.password=pcfhpyylifmfijbd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#  FIX FOR YOUR ERROR (MOST IMPORTANT)
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com